apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-test-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nginx-test-deployment
  template:
    metadata:
      labels:
        app: nginx-test-deployment
    spec:
      containers:
      - name: rollouts-demo
        image: noon-ai-dis.ncr.gov-ntruss.com/noon-ai-dis-web:v0.1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: container-registry-secret
  strategy:
    blueGreen: 
      activeService: nginx-test-deployment-active
      previewService: nginx-test-deployment-preview
      autoPromotionEnabled: false

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-test-deployment-active
spec:
  selector:
    app: nginx-test-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-test-deployment-preview
spec:
  selector:
    app: nginx-test-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80