apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nginx-test-deployment
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: nginx-test-deployment
  targetCPUUtilizationPercentage: 80